### ISSUE TITLE
dotnet new --install ./content works, but doesn't tell you...

### ISSUE THREAD

**Issue by rhires** [JuanGarciaCarmona/AspNetCore21Ang6Template#2]
Hello Juan!

I'm running dotnet core 2.1 on a Mac...and when I run the above command to install the template per your instructions, I get, well, nothing. I get the list of existing templates as if I had typed in an invalid command. 

However, if I type `dotnet new --install .\content` then I get the following: 
`Restoring packages for /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/restore.csproj...
/Users/user/.templateengine/dotnetcli/v2.1.200/scratch/restore.csproj : error NU1101: Unable to find package .content. No packages exist with this id in source(s): /usr/local/share/dotnet/sdk/NuGetFallbackFolder, nuget.org
  Generating MSBuild file /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/obj/restore.csproj.nuget.g.props.
  Generating MSBuild file /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/obj/restore.csproj.nuget.g.targets.
  Restore failed in 444.7 ms for /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/restore.csproj.

  Restoring packages for /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/restore.csproj...
/Users/user/.templateengine/dotnetcli/v2.1.200/scratch/restore.csproj : error NU1101: Unable to find package .content. No packages exist with this id in source(s): /usr/local/share/dotnet/sdk/NuGetFallbackFolder, nuget.org
  Generating MSBuild file /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/obj/restore.csproj.nuget.g.props.
  Generating MSBuild file /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/obj/restore.csproj.nuget.g.targets.
  Restore failed in 362.94 ms for /Users/user/.templateengine/dotnetcli/v2.1.200/scratch/restore.csproj.` 

I assume that the backslash is because you were on a Windows machine, whereas on Mac and Linux it should be a forward slash. 

But then, I tried to run the `dotnet new angular6 -n myTestProject` and it worked. I'm not sure if this is an issue with dotnet core, or something your code doesn't take into account. But I thought I'd let you know. 

(by the way, I suggest that you include the exact version number of dotnet core 2.1.300 as the version to use, since .200 didn't cooperate for some reason)

**Comment by JuanGarciaCarmona** [comment]
Hi, well, I'd say that version 200 was the latest preview and 2.1.300 the
first stable version.

Well, regarding the backslash I don't know what to say... You might try to
see the list of project templates because of you can run dotnet new
angular6 whatever then the template was installed. Please, let me know if
it's listed on a Mac, I don't use to work on a Mac...

By the way thanks for trying that it, I hope it helps you.

Regards,



Juan

**Comment by rhires** [comment]
Yes, it does show up in the list of templates, so this is good! 

![image](https://user-images.githubusercontent.com/12577765/42139548-ede06052-7d5d-11e8-81bd-dd8c8ae3d93a.png)

Thank you for making this template. :-)

**Comment by JuanGarciaCarmona** [comment]
My pleasure @rhires , I enjoyed doing it and you are not the only person that told me that was useful so it has worth the effort a lot. By the way, I'm currently writing a set of articles regarding similar topic (Angular 6 and .Net Core 2.1) but those articles are in Spanish (I have my own small audience, ;) )  Nevertheless, the blog has a translate button that works pretty good and the articles might give you guidance with Identity, Code Coverage, some Docker usage with real examples and some unit testing in the backend side. 

I hope it helps you too: https://juan-garcia-carmona.blogspot.com/ 

(and then I'll close the issue.)
