### ISSUE TITLE
Question about running the project

### ISSUE THREAD

**Issue by rhires** [JuanGarciaCarmona/AspNetCore21Ang6Template#4]
Hello again!

I'm unclear about the best way to run the project. If I run `dotnet run`, the backend site gets run as localhost:58893 and it does show the front end. But when I make changes to the front end (such as removing that map), the page on that port doesn't update, but I look in the log and see that ng serve is running the front end app on a different port, and that is where I can see the change. 

What is the best way to run the project and get a consistent port where if I make changes on the FE it will show?

**Comment by JuanGarciaCarmona** [comment]
Well, that's a real issue in this project, something that I'm not able to solve. My workaround is to run the project using "ng serve" to make pure UI changes so that I can see the changes once I save the file(s), but If I want to make back-end changes then I need to run the app through dotnet framework but, then, I lose auto refresh... And, despite is a bit slow, If I need both then I can run the project using dotnet but build the site using ng build, that refreshes the site.

With Angular previous versions this was done automatically and I hope to find a good mechanism to solve it soon.

**Comment by jasonlloydprice** [comment]
I'm not sure if this is a separate issue or not, but I have an issue when running using Docker. I have attached an image below. I basically downloaded the project. Set dockercompose as start project and hit shift f5. 
I'm running VS 20117 v15.7.6. I've been dealing with this same issue in one of my projects so any help would be greatly appreciated.

![image](https://user-images.githubusercontent.com/2065150/45257806-0ff69380-b37a-11e8-9f46-7c517433fe49.png)

**Comment by JuanGarciaCarmona** [comment]
Well, I'm sure it is a separate issue, look at the message that sais "...
Unable to start npm..."...

That usually means that the container image was not properly set up, you
need to install node and npm, it is easy to find a lot of examples of
compose files (multi step) that solves exact same issue.

I hope you fix it soon.

**Comment by jasonlloydprice** [comment]
I may not have made this clear, but I’m saying that I’m having this issue when I run your solution without any changes. I was wondering if you’re aware that you’re solution is broken?

**Comment by JuanGarciaCarmona** [comment]
Ok, once understood I´ve cloned the solution in a different computer, and I wen't through **ALL the instruction steps** and it worked for me. 

![image](https://user-images.githubusercontent.com/2834629/45262180-2bad7880-b412-11e8-97b9-ebeaea691b1c.png)

I've also reviewed the entire process and how the template creates the docker file and its content according to the name you give to the project, ensuring npm and packages installation.... And after this test in a separated environment, I have to say that the solution works. I don´t know what hint to give you apart on to follow the instructions.
